from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd + '/../include']
if GetDepend(['RT_USING_SERIAL']):
    src = Glob('serial.c')
    group = DefineGroup('DeviceDrivers', src, depend = ['RT_USING_SERIAL'], CPPPATH = CPPPATH)

Return('group')
